### ISSUE TITLE
Are there pre-trained models?

### ISSUE THREAD

**Issue by cthoyt** [Kohulan/DECIMER-Image-to-SMILES#1]
There's some documentation on how to train a model, but not on how to use one. Is there a pre-trained model (e.g. the one presented in your paper) that can be readily downloaded/used? How can this be done?

**Comment by Kohulan** [comment]
Hello @cthoyt ,

I'll try to make it available soon.

Regards,
-Kohulan

**Comment by Kohulan** [comment]
Hello @cthoyt ,

As requested, I have included a trained model that was trained using 15 million images in the repository under Trained models. you can use the Predictor.py script added in the Network folder to predict the desired image. Sample Images are provided.

I hope that helps.

Kind regards,
Kohulan
