### ISSUE TITLE
在https://github.com/Kohulan/DECIMER-Image-to-SMILES/blob/master/Network/I2S_evalData.py第61行代码有错误

### ISSUE THREAD

**Issue by miracle1111111** [Kohulan/DECIMER-Image-to-SMILES#4]
Hello, onlytestI2S_Data.data_loader(PATH,total_data) in the 61st line of I2S_evalData.py, onlytestI2S_Data does not define this package
![2020-12-02 193047](https://user-images.githubusercontent.com/49110370/100867269-ec790f80-34d4-11eb-9c54-15513d11d536.png)

**Comment by Kohulan** [comment]
@miracle1111111 Fixed, use the I2Sdat package and you can use the predictor for ease of use
