### ISSUE TITLE
deepsmiles.exceptions.DecodeError: DeepSMILES cannot be decoded to SMILES

### ISSUE THREAD

**Issue by drscarlat** [Kohulan/DECIMER-Image-to-SMILES#6]
I've cloned to Kaggle and tried it for prediction only - on the samples provided.
For the first time only, it finished working without errors and I found the result in the Predictions file.
But since then, any of the sample images provided - is causing the following error:

```
deepsmiles.exceptions.DecodeError: DeepSMILES cannot be decoded to SMILES
There is no corresponding atom on which to place the ring opening
symbol for the ring sized 8:
  #8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8
```
As the same exact error appears with all sample images, I thought maybe a variable wasn't zeroed, so I restarted the kernel and re cloned it.
Now - it throws this error:

```
deepsmiles.exceptions.DecodeError: DeepSMILES cannot be decoded to SMILES
digit not allowed as first character:
  33333333333333333333333333333333333333333333333333333333333333333333333333
```
Any ideas ?
Thx

**Comment by Kohulan** [comment]
Hello @drscarlat ,

It looks like the Predictor.py couldn't find the model, check whether it is present on the correct folder. Also the images you use should correspond to the ruleset found in the paper. 

If you are trying to use the model to predict the DeepSMILES on the kaggle competition images the model will fail.

-Kohulan

**Comment by drscarlat** [comment]
You're right - Once I've put the trained model in the right folder - Predictor works.
Thanks!
And unfortunately you're right again - the model fails at the BMS Kaggle competition: 
I've tried it with several competition images: translated the SMILES into Mol with rdkit and then from Mol to InChi.
The average Levenshtein distance (used in the competition) is very high...so the model fails, as you've said.

Why is the model failing on these images ?

**Comment by Kohulan** [comment]
The model was not trained on these images, you can train on the provided training images and test.
