### ISSUE TITLE
Retrain the model

### ISSUE THREAD

**Issue by vijayct03** [Kohulan/DECIMER-Image-to-SMILES#8]
Hi,

You provided already trained model,
Could you provide the information how to retrain the model. Because it will be useful for us to train the images which we have.

**Comment by Kohulan** [comment]
Hello @vijayct03 ,

Details regarding how to generate Images the data and to retrain the model is given here: https://github.com/Kohulan/DECIMER-Image_Transformer 
Please refer to this. 

In case if you bump into problems let me know I will try to update you with how to retrain in this repository

-Kohulan
